/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CpapStudyRouteImport } from './routes/cpap-study'
import { Route as ISpyRouteImport } from './routes/i-spy'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as SleepStudyRouteImport } from './routes/sleep-study'
import { Route as ParentsIndexRouteImport } from './routes/parents.index'
import { Route as ParentsHabitsRouteImport } from './routes/parents.habits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CpapStudyRoute = CpapStudyRouteImport.update({
  id: '/cpap-study',
  path: '/cpap-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ISpyRoute = ISpyRouteImport.update({
  id: '/i-spy',
  path: '/i-spy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepStudyRoute = SleepStudyRouteImport.update({
  id: '/sleep-study',
  path: '/sleep-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentsRoute,
} as any)
const ParentsHabitsRoute = ParentsHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => ParentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cpap-study': typeof CpapStudyRoute
  '/i-spy': typeof ISpyRoute
  '/parents': typeof ParentsRouteWithChildren
  '/sleep-study': typeof SleepStudyRoute
  '/parents/habits': typeof ParentsHabitsRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cpap-study': typeof CpapStudyRoute
  '/i-spy': typeof ISpyRoute
  '/sleep-study': typeof SleepStudyRoute
  '/parents/habits': typeof ParentsHabitsRoute
  '/parents': typeof ParentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cpap-study': typeof CpapStudyRoute
  '/i-spy': typeof ISpyRoute
  '/parents': typeof ParentsRouteWithChildren
  '/sleep-study': typeof SleepStudyRoute
  '/parents/habits': typeof ParentsHabitsRoute
  '/parents/': typeof ParentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cpap-study'
    | '/i-spy'
    | '/parents'
    | '/sleep-study'
    | '/parents/habits'
    | '/parents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cpap-study'
    | '/i-spy'
    | '/sleep-study'
    | '/parents/habits'
    | '/parents'
  id:
    | '__root__'
    | '/'
    | '/cpap-study'
    | '/i-spy'
    | '/parents'
    | '/sleep-study'
    | '/parents/habits'
    | '/parents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CpapStudyRoute: typeof CpapStudyRoute
  ISpyRoute: typeof ISpyRoute
  ParentsRoute: typeof ParentsRouteWithChildren
  SleepStudyRoute: typeof SleepStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpap-study': {
      id: '/cpap-study'
      path: '/cpap-study'
      fullPath: '/cpap-study'
      preLoaderRoute: typeof CpapStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-spy': {
      id: '/i-spy'
      path: '/i-spy'
      fullPath: '/i-spy'
      preLoaderRoute: typeof ISpyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep-study': {
      id: '/sleep-study'
      path: '/sleep-study'
      fullPath: '/sleep-study'
      preLoaderRoute: typeof SleepStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof ParentsRoute
    }
    '/parents/habits': {
      id: '/parents/habits'
      path: '/habits'
      fullPath: '/parents/habits'
      preLoaderRoute: typeof ParentsHabitsRouteImport
      parentRoute: typeof ParentsRoute
    }
  }
}

interface ParentsRouteChildren {
  ParentsHabitsRoute: typeof ParentsHabitsRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

const ParentsRouteChildren: ParentsRouteChildren = {
  ParentsHabitsRoute: ParentsHabitsRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}

const ParentsRouteWithChildren =
  ParentsRoute._addFileChildren(ParentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CpapStudyRoute: CpapStudyRoute,
  ISpyRoute: ISpyRoute,
  ParentsRoute: ParentsRouteWithChildren,
  SleepStudyRoute: SleepStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
