/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as ParentsHabitsRouteImport } from './routes/parents.habits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsHabitsRoute = ParentsHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => ParentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parents': typeof ParentsRouteWithChildren
  '/parents/habits': typeof ParentsHabitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parents': typeof ParentsRouteWithChildren
  '/parents/habits': typeof ParentsHabitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parents': typeof ParentsRouteWithChildren
  '/parents/habits': typeof ParentsHabitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parents' | '/parents/habits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parents' | '/parents/habits'
  id: '__root__' | '/' | '/parents' | '/parents/habits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentsRoute: typeof ParentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/habits': {
      id: '/parents/habits'
      path: '/habits'
      fullPath: '/parents/habits'
      preLoaderRoute: typeof ParentsHabitsRouteImport
      parentRoute: typeof ParentsRoute
    }
  }
}

interface ParentsRouteChildren {
  ParentsHabitsRoute: typeof ParentsHabitsRoute
}

const ParentsRouteChildren: ParentsRouteChildren = {
  ParentsHabitsRoute: ParentsHabitsRoute,
}

const ParentsRouteWithChildren =
  ParentsRoute._addFileChildren(ParentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentsRoute: ParentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
